### ISSUE TITLE
Parameter effect and values for reproducing some examples

### ISSUE THREAD

**Issue by ArielReplicate** [timothybrooks/instruct-pix2pix#14]
I get slightly lower quality compared to what is shown project page when using default parameters:

Can you give a hint for what are good values for some of the parameters and explain their effect :

for example what are
```
cfg_text = 7.5
cfg_image = 1.5
```

I got these for some of the examples inputs from the project page (images might also be slightly different then what you used)
![output](https://user-images.githubusercontent.com/116253211/213825812-081c52d4-2486-4c41-98e8-d6f291b46a39.jpg)

for some other inputs like the _"girl with pearl earing"_  the output is unchanged.

should I expect better results with other parameter settings?

Thanks

**Comment by holynski** [comment]
Hey, there are a bunch of parameters that will affect the quality. Take a look at the Tips section in the README. 

As a rule of thumb, you should mess around with varying:
- cfg_image (more will lead to more preservation of the input image, but less drastic edits)
- cfg_text (more will lead to more drastic edits but less variety)
- seed (sometimes, some seeds will edit the image more than others)
- resolution (sometimes, certain resolutions make certain types of changes better)
- edit wording (certain phrasings of the edit instructions work better or worse)
- crop (certain framings of the image work better than others sometimes, especially for faces)

It will be hard to *exactly* replicate any result, just because (1) the model checkpoints are not identical, since the data has been filtered since original submission, (although this doesn't necessarily mean the model is worse, just different) (2) the input images are not identical, (3) the parameters are probably different, and (4) the seed is different. But, I suspect with some tuning you could get something just as good as what's in the paper.

**Comment by timothybrooks** [comment]
+1 to Aleks' points. Also, for the result on this image in the paper, we ran it at a higher resolution (768 on long edge) to show the model's flexibility. So resolution is yet another parameter you can experiment with.

**Comment by ArielReplicate** [comment]
Thanks, 
I played with the other parameters and easily got much better results.
for example
![output (1)](https://user-images.githubusercontent.com/116253211/214145322-91ca06b1-577b-4c70-9ecc-6cbd04d4611e.jpg)
