### ISSUE TITLE
No scale factor applied when concat image related information

### ISSUE THREAD

**Issue by liuliu** [timothybrooks/instruct-pix2pix#36]
Hi, this is a minor nit and asking to see if there are explicit motivations to do so. In the process of supporting this model in Draw Things, I noticed that unlike Inpainting models, where the encoded image multiplied the "scale factor": https://github.com/runwayml/stable-diffusion/blob/main/ldm/models/diffusion/ddpm.py#L550 while in instruct pix2pix, we don't: https://github.com/timothybrooks/instruct-pix2pix/blob/main/edit_cli.py#L103

Not a big deal to me as I figured out, modified a bit and it worked exactly like expected. But want to call it out and see if there are some considerations applied so I know where my modifications should be applied (whether treat the edit model as a special case, or just modify the first layer conv2d weights).

**Comment by holynski** [comment]
Hey, I don't think this was a deliberate choice (@timothybrooks can correct me if I'm wrong here). 

The current pre-trained checkpoints need to use unscaled values for the conditioning image, just because that's how we trained it. But I suspect results would have been comparable had we trained with scaled values instead. My guess is that this just happened to be the first thing we tried, and it worked, so we didn't have a reason to change it.

It certainly might make sense, for consistency with other repositories (and even for consistency with the output images), to use scaled values here, so it might be worth trying to train another model in this configuration.
